export const categories = {
  en: [
    "Animals",
    "Countries",
    "Cities",
    "Book Titles",
    "Movies",
    "Foods",
    "Sports",
    "Professions",
    "Things in a Kitchen",
    "Musical Instruments",
    "Plants",
    "Vehicles",
    "Clothing",
    "Board Games",
    "Weather Words",
    "Technology Terms",
    "School Subjects",
    "Hobbies",
    "Superheroes",
    "Villains",
    "Famous Landmarks",
    "Body Parts",
    "Tools",
    "Colors",
    "Fruits",
    "Vegetables",
    "Desserts",
    "Sea Creatures",
    "Birds",
    "Electronics",
    "Programming Languages",
    "Phone Apps",
    "Websites",
    "Job Skills",
    "Elements",
    "Math Terms",
    "Space Things",
    "Mythical Creatures",
    "Musicians",
    "TV Shows",
    "Brands",
    "Transport Hubs",
    "Boarding Gate Items",
    "Outdoor Gear",
    "Furniture",
    "Beverages",
    "Breakfast Foods",
    "Holidays",
    "Festivals",
    "Historical Figures"
  ]
};
